### ISSUE TITLE
Uncaught InvalidArgumentException when selecting pushTAN

### ISSUE THREAD

**Issue by JuliusFreudenberger** [bnw/firefly-iii-fints-importer#1]
I watched the development of fireflyIII for some time now and are very happy to see a FinTS-importer which made me try a switch from my current system.
I searched a bit for the url and got all the necessary information together.
My bank (Kreissparkasse Tuttlingen) uses the pushTAN-method (app on my smartphone, which works for normal online banking), so I selected it in the importer gui.
Now I get an Exception which says the following
```
Fatal error: Uncaught InvalidArgumentException: tanMedium is mandatory for this tanMode in /home/<user>/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php:634 
Stack trace: #0 /home/<user>/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(654): Fhp\FinTsNew->getSelectedTanMode() 
#1 /home/<user>/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php(243): Fhp\FinTsNew->requireTanMode() 
#2 /home/<user>/firefly-iii-fints-importer/app/index.php(51): Fhp\FinTsNew->login() 
#3 /home/<user>/firefly-iii-fints-importer/app/TanHandler.php(34): {closure}() 
#4 /home/<user>/firefly-iii-fints-importer/app/TanHandler.php(24): App\TanHandler->create_or_continue_action()
#5 /home/<user>/firefly-iii-fints-importer/app/index.php(49): App\TanHandler->__construct()
#6 {main} thrown in /home/<user>/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php on line 634
```
I also tried the other methods:
I don't get the error and it says I successfully connected to the account.
But pulling the data obviously doesn't work, because the TAN-method is wrong.
Only the smsTAN-method also brings the same error.

For me that looks like an internal error getting the data from the gui and doesn't involve the FinTS-part, which should make it not _that_ complicated.. hopefully.
I'm happy to provide more information if needed to help fix this issue.

**Comment by bnw** [comment]
Hi,
sorry for the late reply. Thanks for the feedback. It seems that for some Tan methods one needs to choose a device (e.g. which phone). For the method I use this was not necessary. 
This will require an additional (optional) step in the process in which one can choose one of the tan devices suggested by the bank. I'll try to do some work on this soon.

**Comment by bnw** [comment]
Hi @JuliusFreudenberger,
I added an additional step to let you choose your tan device. Unfortunately, I am unable to test it myself. Could you give it a try?

**Comment by rytilahti** [comment]
This happens when submitting the tan:
```
Fatal error: Uncaught TypeError: Argument 2 passed to Fhp\FinTsNew::submitTan() must be of the type string, null given, called in /app/TanHandler.php on line 32 and defined in /vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php:369 
Stack trace: 
#0 /app/TanHandler.php(32): Fhp\FinTsNew->submitTan(Object(Fhp\Protocol\DialogInitialization), NULL) 
#1 /app/TanHandler.php(24): App\TanHandler->create_or_continue_action() 
#2 /app/index.php(73): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTsNew), Object(App\Step)) 
#3 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/FinTsNew.php on line 369
```

Also, the tan request page has an unrelated warning (`Notice: Undefined variable: challengeImageSrc in /app/TanHandler.php on line 65`),

**Comment by bnw** [comment]
Thanks. I tried to fix both. Could you check again?

**Comment by rytilahti** [comment]
Thanks, it seems to be working (or at least I got something imported)! :100: There was one non-obvious issue for a real transaction with an empty desc (`The description field is required.`), but that is likely coming from firefly-iii?

**Comment by bnw** [comment]
Nice, thanks for testing. :)

Yes, thats a message relayed from Firefly. 
In a transaction there are several fields that could be used as the description. For me, the field that is currently used has the most meaningful value.
I added some more debug code, that shows the full transaction data upon failure. For the transaction in question, you could check this data if there is another field that holds a meaningful description. 
If yes, I can make the importer use this for a backup description.
Notice that firefly automatically avoids importing the same transaction twice.

**Comment by rytilahti** [comment]
Thanks for working on this, my setup has been on hold since we lost fints access :-)

The builds are not working anymore (and even removing composer.lock didn't seem to fix it), any ideas?
```
$ docker-compose build
Building app
Step 1/6 : FROM php:7.3-cli-alpine
 ---> 9210c96214b3
Step 2/6 : RUN apk add composer git
 ---> Using cache
 ---> e90e2913fd06
Step 3/6 : COPY . .
 ---> 4b11088e5575
Step 4/6 : RUN composer install
 ---> Running in 6f7a0835ee0d
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-bcmath * is missing from your system. Install or enable PHP's bcmath extension.

ERROR: Service 'app' failed to build: The command '/bin/sh -c composer install' returned a non-zero code: 2
```

**Comment by bnw** [comment]
Ah, my bad for not testing the docker build.
I added the missing requirement and it builds now. 

As for an empty description field:  
According to the api, the description is mandatory.
See: https://api-docs.firefly-iii.org/#/transactions/storeTransaction
I've added a fallback description that should solve most cases.

**Comment by JuliusFreudenberger** [comment]
I tested it too, and I could import my data successfully with pushTAN and a smartphone as device!
Thanks!!
