### ISSUE TITLE
Empty account list at Postbank

### ISSUE THREAD

**Issue by nr458h** [bnw/firefly-iii-fints-importer#10]
Hi all

I tried to setup my postbank account with this information
'https://hbci.postbank.de/banking/hbci.do'
10010010

I can now go to the next step but when I try to select a banking account the list is empty

If I can provide additional information - please point me where to get them

Thanks anyway

**Comment by bnw** [comment]
Hi,
if you don't get any error messages, I suspect you don't provide the login information your bank expects.  
You could try the following:
* Make sure your account is not blocked, aka successfully login into your regular online banking.
* In the importer, assert that entering a wrong pin yields an error message.
* Try different TAN methods (did it ask you for any TANs)?
* As noted [here](https://www.willuhn.de/wiki/doku.php?id=support:list:banken:misc:pintan#postbankpin_tan), you might need to add parts of your account number to your login name.

**Comment by nr458h** [comment]
Thanks for the very fast answer.

I still don't get any error message :(
- I ensured, my account is not blocked
- if I enter the wrong password, I get the error: could not determine system id
- And I'm not asked for any TAN Method - thats weird

From your linked help page I found that this could be related to shared accounts and tried to login with a subaccount ending up with an empty selection field
- and I increased the value for banking software to 2000€

Any other ideas?

**Comment by bnw** [comment]
Hm, unfortunately, not really. 
The fact that two different login names resulted in the same problem lets me believe that your settings are still not correct.
Some vague ideas:
* You could try if accessing your account works with one of the other (possibly commercial) financial softwares out there. (Maybe there are some that offer a free tier?) You could also try to find out if they recommend special settings for your bank (like in the link I posted).
* You could try to work directly with the library this importer uses: 
https://github.com/nemiah/phpFinTS/
You could try to get https://github.com/nemiah/phpFinTS/blob/master/Samples/statementOfAccount.php working by playing around with the various methods and settings it offers.
* Maybe the easiest step forward would be to contact your bank. With my bank I had good experiences with that. They were able to even answer very specific technical questions.

**Comment by camelmann** [comment]
Worked with me with the following setting, you need to use "bank_2fa": "930" which is not available through the GUI

```
{
  "bank_username": "POSTPANK ID",
  "bank_password": "PASSWORD",
  "bank_code": "10010010",
  "bank_url": "https://hbci.postbank.de/banking/hbci.do",
  "bank_2fa": "930",
  "firefly_url": "YOUR_SERVER",
  "firefly_access_token": "YOUR_TOKEN"
}
```

**Comment by bnw** [comment]
Added to the gui :+1:
