### ISSUE TITLE
DKB debit card IBAN

### ISSUE THREAD

**Issue by mtettke123** [bnw/firefly-iii-fints-importer#100]
the DKB gives the "ghost" IBAN DE96120300009005290904 to all payments made with the VISA debit card. This leads to the fact that all payments are assigned to the wrong incoming account (All to the same). An easy fix could be to be able to just ignore specific IBANs and just leave the field blank when importing to firefly...

**Comment by bnw** [comment]
I think this sounds like a good use case for firefly's rules engine.
https://docs.firefly-iii.org/firefly-iii/features/rules/
