### ISSUE TITLE
Blank page after "Import transaction to firefly iii"

### ISSUE THREAD

**Issue by chises** [bnw/firefly-iii-fints-importer#103]
Hello,

I started with firefly iii and the fints importer (docker).
Two bank accounts are working fine, one is not.
The bank account that is not working is at the "Postbank" (Germany).
I limited it to a single day and 2 transactions within that day:
![image](https://github.com/bnw/firefly-iii-fints-importer/assets/10805806/43a40661-00df-4aaa-ab18-4ab02eb7e6be)

![image](https://github.com/bnw/firefly-iii-fints-importer/assets/10805806/2e256687-71f8-4cc8-b743-adcfb254b8a3)

After the import only a white page shows up. No errors on the docker container or in Javascript:
```
[Tue Jul  4 19:51:16 2023] 172.17.1.223:3293 Accepted
[Tue Jul  4 19:51:16 2023] 172.17.1.223:3294 Accepted
[Tue Jul  4 19:51:16 2023] 172.17.1.223:3294 Closing
[Tue Jul  4 19:51:16 2023] 172.17.1.223:3293 Closing
[Tue Jul  4 19:51:30 2023] 172.17.1.223:3310 Accepted
[Tue Jul  4 19:51:30 2023] 172.17.1.223:3311 Accepted
[Tue Jul  4 19:51:30 2023] 172.17.1.223:3310 Closing
[Tue Jul  4 19:51:30 2023] 172.17.1.223:3311 Closing
[Tue Jul  4 19:51:34 2023] 172.17.1.223:3314 Accepted
[Tue Jul  4 19:51:34 2023] 172.17.1.223:3313 Accepted
[Tue Jul  4 19:51:41 2023] 172.17.1.223:3314 Closing
[Tue Jul  4 19:51:41 2023] 172.17.1.223:3313 Closing
[Tue Jul  4 19:51:43 2023] 172.17.1.223:3320 Accepted
[Tue Jul  4 19:51:47 2023] 172.17.1.223:3320 Closing
[Tue Jul  4 19:51:47 2023] 172.17.1.223:3322 Accepted
[Tue Jul  4 19:51:47 2023] 172.17.1.223:3322 Closing
[Tue Jul  4 19:51:49 2023] 172.17.1.223:3327 Accepted
[Tue Jul  4 19:51:49 2023] 172.17.1.223:3328 Accepted
[Tue Jul  4 19:51:52 2023] 172.17.1.223:3327 Closing
[Tue Jul  4 19:51:52 2023] 172.17.1.223:3328 Closing
[Tue Jul  4 19:51:55 2023] 172.17.1.223:3333 Accepted
[Tue Jul  4 19:51:55 2023] 172.17.1.223:3334 Accepted
[Tue Jul  4 19:51:59 2023] 172.17.1.223:3333 Closing
[Tue Jul  4 19:51:59 2023] 172.17.1.223:3334 Closing
```

Any hint how to identify the problematic entry and how to fix this? I think it is the "Bargeldauszahlung" (cash withdrawal) on a cash terminal.
This configuration file is used:
```
cat /app/configurations/post.json 
{
  "bank_username": "account",
  "bank_password": "password",
  "bank_code": "10010010",
  "bank_url": "https://hbci.postbank.de/banking/hbci.do",
  "bank_2fa": "920",
  "firefly_url": "http://172.17.1.11:8081",
  "firefly_access_token": "myAccessToken",
  "skip_transaction_review": "false",
  "description_regex_match": "///mi",
  "description_regex_replace": "",
  "choose_account_automation":
  {
    "bank_account_iban": "myIBAN",
    "firefly_account_id": "27",
    "from_to_comment": "The following values will be passed directly into DateTime",
    "from": "now - 36 days",
    "to": "now - 36 days"
  }
}
```
It is limited to _now - 36 days_ because that is the day with the two entrys listed above.

**Comment by bnw** [comment]
Hi,

thanks a lot for your report!

Strange. One thing that strikes me in your config is the `"description_regex_match": "///mi",`.
I'm not sure if this is a valid regex search pattern. If you want to disable the regex matching, set it to null.

But I'm not sure this is the problem here. 
It is strange that you get a blank page, because in the docker container, PHP is configured to output any errors.
Could you try the following?
In `app/TransactionsToFireflySender.php` after the `foreach` loop in line 124, add the following line: 
`var_dump($transaction);`.
A few lines later, after `$response = $request->post();`, add the line `var_dump($response);`.

The output of these debug messages should now appear on the page after you click "Import transactions to FireflyIII". 
You might need to look at the HTML source to see them (right click -> view page source (or similar)).

Thanks a lot for your help.

**Comment by chises** [comment]
Hello @bnw,

thank you for your support here and sorry for my late response. 
I modified the regex to something else, same result:
```
"description_regex_match": "/^(Ãœbertrag \\/ Ãœberweisung|Lastschrift \\/ Belastung)(.*)(END-TO-END-REF.*|Karte.*|KFN.*)(Ref\\..*)$/mi",
```
I adjusted the source code as requested:
![image](https://github.com/bnw/firefly-iii-fints-importer/assets/10805806/ba4cc0b6-9f8c-4bf9-85d0-26fee68bdd3f)

This is the ouput on the website:
```
Transactionobject(Fhp\Model\StatementOfAccount\Transaction)#119 (16){
   [
      "bookingDate":"protected"
   ]=> object(DateTime)#120 (3){
      [
         "date"
      ]=> string(26)"2023-05-30 00:00:00.000000"[
         "timezone_type"
      ]=> int(3)[
         "timezone"
      ]=> string(3)"UTC"
   }[
      "valutaDate":"protected"
   ]=> object(DateTime)#121 (3){
      [
         "date"
      ]=> string(26)"2023-05-29 00:00:00.000000"[
         "timezone_type"
      ]=> int(3)[
         "timezone"
      ]=> string(3)"UTC"
   }[
      "amount":"protected"
   ]=> float(1000)[
      "creditDebit":"protected"
   ]=> string(6)"credit"[
      "isStorno":"protected"
   ]"=> bool(false)"[
      "bookingCode":"protected"
   ]=> string(3)"166"[
      "bookingText":"protected"
   ]=> string(0)""[
      "description1":"protected"
   ]=> string(22)"EREF+CCB.147.UE.151999"[
      "description2":"protected"
   ]=> string(0)""[
      "structuredDescription":"protected"
   ]=> array(1){
      [
         "EREF"
      ]=> string(17)"CCB.147.UE.151999"
   }[
      "bankCode":"protected"
   ]=> string(0)""[
      "accountNumber":"protected"
   ]=> string(22)"DE93530800300777797800"[
      "name":"protected"
   ]=> string(35)"KLAUS DIETER WEBER ODER RENATE WEBE"[
      "booked":"protected"
   ]"=> bool(true)"[
      "pn":"protected"
   ]=> int(0)[
      "textKeyAddition":"protected"
   ]=> int(0)
}
```
There is no _response_ at all. Any idea here?

**Comment by chises** [comment]
I found it, I am at this line:
https://github.com/bnw/firefly-iii-fints-importer/blob/master/app/TransactionsToFireflySender.php#L96

In this transaction the description and bootkingText is empty. So the transaction is stuck at Line 96 :)

I try to fix it/create a workaround and create a PR. Thank you so far!

**Comment by bnw** [comment]
Thanks a lot for your investigations and the MR :)
