### ISSUE TITLE
Cant find a  "firefly_account_id" for the config.json

### ISSUE THREAD

**Issue by Borega** [bnw/firefly-iii-fints-importer#106]
Where can I find that ID? I tried all kinds of IDs that I could find but they were all wrong. What ID is used here and where can I find it?

**Comment by bnw** [comment]
This is the id of your account in firefly. If you are the only person using your firefly instance, your account id is most likely 1.
You can see your firefly account id in firefly: Options -> Profile -> "Your user id is X"

**Comment by Borega** [comment]
"Could not find the Firefly ID "1" in your Firefly III account.
Please review your configuration."
but at the same time:
"Your user id is 1"
when looking at Options -> Profile ->

**Comment by DanielVolz** [comment]
You can find the firefly account id under Accounts-> Asset Account by hovering over the link in the "Name" column. If there is no asset account, you have to create one first by yourself.

The link will look similar to "https://firefly.local/accounts/show/12". The number (here 12) is the account id of the selected asset account.
