### ISSUE TITLE
Import cancels unexpectedly

### ISSUE THREAD

**Issue by dklinger** [bnw/firefly-iii-fints-importer#109]
Hi.
For one of my accounts, the import stops unexpectedly.
By checking the dates of the transactions, which were the last ones imported before the import stopped, it looks like fints-importer may have a problem if firefly has a rule to instantly delete an imported transaction.

Steps to reproducs:
- Setup a rule to delete an incoming transaction, if it is of type "Transfer" (Not sure if the type is important or not)
- Execute a FinTS-import which triggers the rule

**Comment by dklinger** [comment]
To add to this:
The current behaviour is, that the browser page is just white and nothing is happening.
If I then hit F5 and confirm that I want to resent the data, it looks looks it picks up the import again but if another "failing" transaction is hit, the page becomes white again. I can keep going hitting F5 until the import is finished. 
But I don't think this should be the expected behaviour, should it?

**Comment by PBue** [comment]
Hi,
I experienced a similiar behavior, except I have not configured such a "delete rule". I have a fresh setup and no transactions in my accounts (DKB) in firefly.
fints-importer fetches all statements from my banking account correctly and lists them before proceeding. After pressing "Import transactions to FireflyIII" the screen turns white and nothing happens. Refreshing the page does not work for me.

The firefly-iii-core logs say:
`172.21.0.5 - - [16/Sep/2023:19:07:17 +0200] "GET /api/v1/accounts?type=asset&page=1&limit=250 HTTP/1.1" 200 3916 "-" "GuzzleHttp/7"
[2023-09-16 19:07:17] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Attempt to read property \"accountType\" on null","time":"Sat, 16 Sep 2023 19:07:17 +0200","file":"\/var\/www\/html\/app\/Validation\/AccountValidator.php","line":280,"code":0,"version":"6.0.24","url":"http:\/\/app:8080\/api\/v1\/transactions","userAgent":"GuzzleHttp\/7","json":true,"method":"POST"}  
[2023-09-16 19:07:17] local.ERROR: Attempt to read property "accountType" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"accountType\" on null at /var/www/html/app/Validation/AccountValidator.php:280)
[stacktrace][...]`

Does this help in identifying the problem? This may also be a different problem than @dklinger s

**Comment by Benniphx** [comment]
same error here with dkb data

`[2023-09-17 18:11:06] production.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Attempt to read property \"accountType\" on null","time":"Sun, 17 Sep 2023 18:11:06 +0200","file":"\/var\/www\/html\/app\/Validation\/AccountValidator.php","line":280,"code":0,"version":"6.0.24","url":"http:\/\/192.168.178.88:6182\/api\/v1\/transactions","userAgent":"GuzzleHttp\/7","json":true,"method":"POST"}  
[2023-09-17 18:11:06] production.ERROR: Attempt to read property "accountType" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"accountType\" on null at /var/www/html/app/Validation/AccountValidator.php:280)`

**Comment by Benniphx** [comment]
I solved the problem by using for firefly not the latest image
Image [version-6.0.20] works fine, so switch your docker image, and it should work till @bnw fixes the breaking API error. I would, but I am more a python guy and not a PHP dude.

**Comment by baflo** [comment]
Can confirm it works again on 6.0.20

**Comment by baflo** [comment]
For me it turned out that my installation of fints-importer was outdated. I use F3 and the importer as Home Assistant addons and the importer-addon I used from Alex Belgium is outdated. After I fiddled a up to date version, it worked again. Also with F3 v6.0.24

**Comment by bnw** [comment]
@Benniphx Are you using an old version of the importer, like @baflo?

**Comment by TyrionWarMage** [comment]
This is fixed in Firefly v6.0.25 and higher: https://github.com/firefly-iii/firefly-iii/issues/7973

**Comment by dklinger** [comment]
@bnw Happens again as of FireFly 6.1.1

@TyrionWarMage @baflo @Benniphx : Can you confirm?

**Comment by baflo** [comment]
@dklinger I am on 6.1.0, yet, which still works.

**Comment by Benniphx** [comment]
I have FireFly 6.1.1 and it works all fine so can not confirm what it is not working

**Comment by TyrionWarMage** [comment]
@dklinger Can confirm working for 6.1.0
