### ISSUE TITLE
Save settings (as presets) and/or automate things?

### ISSUE THREAD

**Issue by totti4ever** [bnw/firefly-iii-fints-importer#11]
So, I sucessfully imported now - but of course I would want to repeat that regularly.

But I have to enter all parameters again, which is especially uncomfy for the token. Maybe it'd be a good idea to save those settings as presets, one can select and then maybe bulk-start? That's how I use my current Software MoneyMoney right now and it just asks for the several photoTANs.

thanks for the great import tool, way easier than fetching CSV and importing them!

**Comment by JuliusFreudenberger** [comment]
This may be implemented as command, which can be added as cronjob to be executed daily.
Would be happy to see this feature.

**Comment by totti4ever** [comment]
Well, I'd have to start it manually because of the photo and pushTANs. But being able to define presets per account and define which presets should be started would help heaps!

**Comment by bnw** [comment]
I'll think about it. :)

**Comment by totti4ever** [comment]
Okay, so after experimenting a bit with the spectre importer, I am back to the FinTS importer because Spectre doesn't deliver what I was hoping for: cronjob compability...there one also has to start the job manually and confirm the updates via PhotoTAN apps for my bank accounts.

But, to be able to us this FinTS importer I (and I would be surprised if not everybody) needs the possiblity to start several imports without entering the Details into the web UI bit by bit:

# store configurations in json files (as the other FF importer do) on the server
# a list with check boxes in the UI where one can select the configs to use
# a start button


Any chance?! :-) :-)

**Comment by bnw** [comment]
Please check out [joBr99's](/joBr99) MR #22 :)
