### ISSUE TITLE
DKB not working

### ISSUE THREAD

**Issue by tobikris** [bnw/firefly-iii-fints-importer#12]
I cannot get the importer to work with my account with DKB.

I think that you are also using DKB but I am receiving errors for both pushTAN with the login user with the _p and also the chipTAN method with _c. I would expect to be asked for the pushTAN device as seen in another PR.
Instead I get the following error directly:
```
 Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9210 (wrt seg 3): Auftrag abgelehnt. ([redacted]) FinTS warnings: 3938 (wrt seg 3): Ihr Zugang ist vorläufig gesperrt - Bitte PIN-Sperre aufheben. Request segments: HKTAB:3:4+0+A' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:73 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(355): Fhp\Protocol\ServerException->extractErrorsForReference(Array) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(312): Fhp\FinTs->sendRequestForAction(Object(Fhp\Protocol\GetTanMedia), Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(497): Fhp\FinTs->execute(Object(Fhp\Protocol\GetTanMedia)) #3 /app/index.php(54): Fhp\FinTs->getTanMedia(Object(Fhp\Segment\TAN\VerfahrensparameterZweiSchrittVerfahrenV6)) #4 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 73
```

chipTAN error:
```
 Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9010 (global): Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet. 9010 (wrt seg 4): PIN/TAN Prüfung fehlgeschlagen 9931 (wrt seg 4): Anmeldename oder PIN ist falsch. FinTS warnings: 3920 (wrt seg 4): Zugelassene Zwei-Schritt-Verfahren für den Benutzer. [910, 911, 912, 913] Request segments: HKVVB:4:3+8+0+0+[redacted]+1.0' HKVVB:4:3+8+0+0+[redacted]+1.0' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(353): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(312): Fhp\FinTs->sendRequestForAction(Object(Fhp\Protocol\DialogInitialization), Object(Fhp\Protocol in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196
```

Is your connection still working?

**Comment by rytilahti** [comment]
Looking at the error messages, the first one says
> Ihr Zugang ist vorläufig gesperrt - Bitte PIN-Sperre aufheben.
and the second one:
> Anmeldename oder PIN ist falsch.

Are you sure your account is not suspended (for the first one) and that the credentials are correct for the chiptan?

**Comment by tobikris** [comment]
Sorry, that was a very bad issue... I tried several times which suspended my account and then didn't read the error message again. Before it was saying that it is not able to authenticate me - only the method 921 can be used (which is pushTAN, which I used). I would guess that the device is missing for the API to let me in.

Here is the correct error message for the pushTAN login after unlocking the account:

> Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9010 (global): Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet. 9010 (wrt seg 4): PIN/TAN Prüfung fehlgeschlagen 9931 (wrt seg 4): Anmeldename oder PIN ist falsch. FinTS warnings: 3920 (wrt seg 4): Zugelassene Zwei-Schritt-Verfahren für den Benutzer. [921] Request segments: HKVVB:4:3+8+0+0+[redacted]+1.0' HKVVB:4:3+8+0+0+[redacted]+1.0' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(353): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(312): Fhp\FinTs->sendRequestForAction(Object(Fhp\Protocol\DialogInitialization), Object(Fhp\Protocol\Message)) #3 / in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196

**Comment by tobikris** [comment]
To be sure that I am using the correct login credentials: I am using my login name used also in the web ui as well as the password that I use there. The "Legitimations-ID" DKB is issuing is not needed, right?

**Comment by bnw** [comment]
I'm using chipTAN and this works when I use the *_c username and password, just like in the web UI. I do not need the  "Legitimations-ID".

I think the key message here is "Anmeldename oder PIN ist falsch.", i.e. the TAN generation/verification has not yet started and is not the problem.  
[Here](https://www.aquamaniac.de/rdm/issues/12) somebody had problems with special characters in the password. Could that be the issue here?
