### ISSUE TITLE
What is `auto_submit_form_via_js` doing?

### ISSUE THREAD

**Issue by martinspaniol** [bnw/firefly-iii-fints-importer#125]
In the [example json configuration](https://github.com/bnw/firefly-iii-fints-importer/blob/58a67ef0dd74013088e928fb64e96179a650e12e/data/configurations/example.json#L14) you are providing there's the following line:
```json
"auto_submit_form_via_js": false
```
What is this setting doing? I could not find any documentation on this.

**Comment by jadyndev** [comment]
It sends (some) forms automatically, usually when there is only one option
