### ISSUE TITLE
Inconsistency between configuration file directory leads to broken automation

### ISSUE THREAD

**Issue by Kovah** [bnw/firefly-iii-fints-importer#128]
I just tried to make the automation working. At the moment, it seems to be impossible to get this working properly when running the Importer inside Docker.

- Configuration files need to be located at either `/app/configurations` or `data/configurations` to be loaded for manually running them.
- When mounting the configurations to `/app/configurations` inside Docker, I am able to select them to be run manually, but they are not found when using the automation.
- Mounting the files to `/app/data/configurations` inside Docker, I am neither able to select them manually, nor use them for automation. 

These issues are caused by having two separate configuration dirs that differ between absolute and relative paths.

If you agree, I can submit a pull request to use `/configurations` as the primary directory loading the configurations from, **but relative to where the script is located**: `__DIR__ . '/configurations'`

- Inside Docker it would be `/configurations`, while the app itself is located at `/app`
- When the app is located at `/var/www/importer/app` it would be `/var/www/importer/configurations`

---

Related: #116

**Comment by Toxo666** [comment]
Thank you for the explanation.
Is there a workarround without your PR?

**Comment by Kovah** [comment]
I guess not. The thing is that there are two different configurations that are not compatible with each other. As long as no code is changed, users probably have to choose either option.

**Comment by GermanCoding** [comment]
I changed my docker compose to do the following:

```
volumes:
      - <local volume>:/data/configurations
```

This way the config files where accessible both to automation and in the web UI for manual runs.

**Comment by Kovah** [comment]
Interesting. I tried exactly that (assuming you have the configurations in that local folder without subfolders). But the manual page did not show the configs.

**Comment by GermanCoding** [comment]
Note the leading `/` before data/configurations, this is mapped into the container's root directory (and not under /app). It shows up like this in the UI:

![screenshot](https://github.com/bnw/firefly-iii-fints-importer/assets/4279661/6fd77741-b89a-4749-b634-11cb5c9a0886)

Note that while the UI shows path + filename, for automation you must still only use the filename (and no directory information). It's kinda weird but it works, so I'm not complaining.

**Comment by bnw** [comment]
Hi @Kovah, 
sorry for the late reply. 
Thanks a lot for all the work you put into this.
Unfortunately, I'm hesitant to merge anything that might break people's existing setups. 
Correct me if I'm wrong, but I think, as @GermanCoding explained it above, the automation does work inside docker (with the weird part that you only should put in the file-name, instead of full path). But this is kinda what is [explained in the readme](https://github.com/bnw/firefly-iii-fints-importer#headless-usage). So I don't see any need to change anything here.
Or did I miss one of your points?

**Comment by Kovah** [comment]
Fine for me. Totally understand that possibly breaking existing setups is not worth the little improvement.
However, I think the readme could be improved as I was really confused and had a hard time figuring out the correct setup with paths in Docker.

**Comment by aflegler** [comment]
I also have a Docker container with the following entry in my docker-compose.yaml file:

```
volumes:
- /data/firefly-iii-fints-importer/configurations:/data/configurations
```

As far as I know, this is simply a mapping. `/data/configurations` is used within the container, Docker automatically points to the host directory `/data/firefly-iii-fints-importer`.

So bnw/firefly-iii-fints-importer#216 worked for me.
Please correct me, if I am wrong.
