### ISSUE TITLE
ING import causing an exception

### ISSUE THREAD

**Issue by lukkigi** [bnw/firefly-iii-fints-importer#13]
Hello,

I seem to be having a problem when using the importer with an ING account. I found this issue (https://github.com/nemiah/phpFinTS/issues/57) for using ING with the FinTs package, but I can't seem to get it work with the NoPsd2TanMode. Can you assist me with this?

`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9800 (global): Der Dialog wurde abgebrochen. 9400 (global): Der anonyme Dialog wird nicht unterstützt. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(576): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(602): Fhp\FinTs->ensureBpdAvailable() #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(464): Fhp\FinTs->ensureTanModesAvailable() #4 /app/FinTsFactory.php(48): Fhp\FinTs->getTanModes() #5 /app/FinTsFactory.php(29): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #6 /app/index.php(46): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #7 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196`

Thanks.

**Comment by bnw** [comment]
Hey lukkigi,
man, INGs API seems quite messed up 😅 .
I've added a special tan option to activate the workaround developed in https://github.com/nemiah/phpFinTS/issues/57
Could you give it a try?

**Comment by lukkigi** [comment]
It's working perfectly now. Thanks a lot for the quick help!
