### ISSUE TITLE
how to set up account for fints-importer (so that balance matches)?

### ISSUE THREAD

**Issue by prankousky** [bnw/firefly-iii-fints-importer#132]
Hi,

I just installed firefly-iii-fints-importer and imported my bank statements from ING-DiBa. Firefly-iii was also a fresh install, so I created an account with the IBAN matching my fints-import and ran the import.

My account balance was, let's say, EUR 300. But in firefly-iii, the account balance was -1200 EUR. So a completely different amount. 

I was not able to manually correct this. Can somebody please explain to me the steps I need to follow to

* set up a bank account in firefly-iii (with no manually added data)
* import data via firefly-iii-fints-importer
* match the account balance in firefly-iii with the imported data with the actual account balance on my bank account

Thank you in advance for your help :)

**Comment by JuliusFreudenberger** [comment]
Here's what I did. This is several years ago now, so my steps may be slightly different now and your mileage may vary.
1. Create account in firefly
2. Set and initial balance date and initial balance (balance at this date). -> I used January 1st here, even though I setup firefly in March or so.
3. Start importing statements from this initial date onward.

My setup was pre-PSD 2, so if this applicable to you, keep in mind that you might not be able to import statements older than 90 days.

**Comment by mauricego** [comment]
Completlie unrelated but what did you do to import the data from ING?
URL: https://fints.ing.de/fints
BLZ: 50010517
Username: 10 digit number
Password: your online banking pin
Two-Factor Method: None

Is this right? Because I always get `Fatal error: Uncaught Fhp\CurlException: Failed connection to https://fints.ing.de/fints`
