### ISSUE TITLE
DKB pushTan (921) no input for TAN, 

### ISSUE THREAD

**Issue by ruegr** [bnw/firefly-iii-fints-importer#141]
When trying to import data from DKB I unfortunately have no possibility to enter a tan and just get an error.

taken steps:
1. fill out forms on page "Enter account data"
2. page "Choose a device for your tan method." appears, two (known) Tan Devices are selectable
3. After selecting a Tan Device there ist just a button "Collect statements from your bank"
4. After pressing this button the following error message appears:
`Fatal error: Uncaught AssertionError: Missing value in sessions for: bank_url in /app/FinTsFactory.php:19 Stack trace: #0 /app/FinTsFactory.php(19): assert(false, 'Missing value i...') #1 /app/Login.php(17): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 /app/index.php(61): App\StepFunction\Login() #3 {main} thrown in /app/FinTsFactory.php on line 19`

I tried the precedure multiple times with different browsers and in incognito-mode - no success.

**Comment by bnw** [comment]
Hi,
thanks for your report. I can confirm it.
It seems to be caused by #120 (cc @TyrionWarMage).
I reverted that change and now it is working again for me. Could you confirm, @ruegr? :)

**Comment by ruegr** [comment]
> I reverted that change and now it is working again for me. Could you confirm, @ruegr? :)

Works for me now, too!
Thanks a lot for the super fast fix!
