### ISSUE TITLE
[Documentation] Where to add additional documentation for a specific Bank

### ISSUE THREAD

**Issue by 89Q12** [bnw/firefly-iii-fints-importer#143]
I'm using this for IngDiBa, as I recently changed my password using their website to one with **more** than 10 characters.
This results in this error:
`
<b>Fatal error</b>:  Uncaught Fhp\Protocol\ServerException: FinTS errors:
9800 (global): Der Dialog wurde abgebrochen.
9942 (global): Anmeldung nur mit 10-stelliger Kontonummer und 5 bis 10-stelliger PIN möglich. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170
Stack trace:
#0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message))
#1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs-&gt;sendMessage(Object(Fhp\Protocol\Message))
#2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(832): Fhp\FinTs-&gt;execute(Object(Fhp\Protocol\DialogInitialization))
#3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(705): Fhp\FinTs-&gt;executeWeakDialogInitialization(NULL)
#4 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(259): Fhp\FinTs-&gt;ensureSynchronized()
#5 /app/Login.php(23): Fhp\FinTs-&gt;login()
#6 /app/TanHandler.php(41): App\StepFunction\{closure}()
#7 /app/TanHandler.php(31): App\TanHandler-&gt;create_or_continue_action()
#8 /app/Login.php(21): App\TanHandler-&gt;__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request))
#9 /app/index.php(59): App\StepFunction\Login()
#10 {main}
  thrown in <b>/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php</b> on line <b>170</b><br />
`

Where should I add documentation that a password between 5 and 10 characters is needed for IngDiBa to function?

(I think that adding this under tips is a good place.)

**Comment by bnw** [comment]
Oh man, that's an annoying error :D

Having some bank-specific tips is probably a good idea. How about a section "Bank specifics" or similar at the end of the Readme?

**Comment by 89Q12** [comment]
Yeah good point!
Will do a PR once I come around to it, thanks for the timely input :)
