### ISSUE TITLE
Add pushTan 2.0

### ISSUE THREAD

**Issue by gaincoder** [bnw/firefly-iii-fints-importer#146]
Please add pushTan 2.0 

It's code is 923. It's the default for Sparkasse (App S-pushTAN) in Germany

The request seems to work like pushTan (it already appears in the app) but the main difference is that there's no tan-code to copy, but an accept button in the app which sends a feedback to the backend

**Comment by bnw** [comment]
Hi @gaincoder,
if you like, you could try out if it works out of the box with the library that this importer uses:
- Clone the repository 
- Edit app/public/html/collecting-data.twig to add the 923 option
- Start the app, e.g. by building the docker image (see readme)
If we are lucky, this just works :)

**Comment by bnw** [comment]
Nevermind, it was just added here:
https://github.com/bnw/firefly-iii-fints-importer/pull/145
Feel free to test the new release :)
