### ISSUE TITLE
configuration.json doesn't work with ING

### ISSUE THREAD

**Issue by mauricego** [bnw/firefly-iii-fints-importer#148]
I always get the following error:

`
Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9800 (global): Der Dialog wurde abgebrochen. 9400 (global): Der anonyme Dialog wird nicht unterstützt. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(645): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(673): Fhp\FinTs->ensureBpdAvailable() #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(532): Fhp\FinTs->ensureTanModesAvailable() #4 /app/FinTsFactory.php(55): Fhp\FinTs->getTanModes() #5 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #6 /app/CollectData.php(61): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #7 /app/index.php(51): App\StepFunction\CollectData() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`

This is my configuration.json:
`{
  "bank_username": “10 digit number”,
  "bank_password": “password”,
  "bank_code": "50010517",
  "bank_url": "https://fints.ing.de/fints",
  "bank_2fa": "NoPsd2TanMode",
  "bank_2fa_device": "",
  "firefly_url": "http://url”,
  "firefly_access_token": "",
  "skip_transaction_review": "false",
  "__description_regex_comment__": "To disable the regex search & replace of the transaction description, set both to an empty string.",
  "description_regex_match": "",
  "description_regex_replace": "",
  "auto_submit_form_via_js": true,
  "choose_account_automation":
  {
    "bank_account_iban": “Iban”,
    "firefly_account_id": "Geldbörse",
    "__from_to_comment__": "The following values will be passed directly into DateTime. Set them to null to choose them manually during import process.",
    "from": "now - 10 days",
    "to": "now"
  }`

I suspect it has something to do with the field `bank_2fa`?
Using the manual mode with the same data as in the .json file works without problems.

**Comment by bnw** [comment]
How did you solve your issue, @mauricego ? :)

**Comment by mauricego** [comment]
It was a long day and I didn't realize that I edited a different configuration.json file in a different path all the time :( 
The error was because it was always using a faulty configuration.json file, and all changes I made were in a different path to another file. It works perfectly fine now with the configuration as above.
