### ISSUE TITLE
Support for Multiple ibans within single account

### ISSUE THREAD

**Issue by Net-Felix** [bnw/firefly-iii-fints-importer#153]
My Banking Login has multiple ibans assigned to it, is it possible to autoimport all within a single configuration?

eg:
```
{
  ...,
  "choose_account_automation":
  [
    {
      "bank_account_iban": "DE11111111111111111111",
      "firefly_account_id": "1",
      "__from_to_comment__": "",
      "from": "now - 7 days",
      "to": "now"
    },
    {
      "bank_account_iban": "DE22222222222222222222",
      "firefly_account_id": "2",
      "__from_to_comment__": "",
      "from": "now - 7 days",
      "to": "now"
    }
  ]
}
```

**Comment by bnw** [comment]
Hi,
I think that to cover this scenario it would be easiest to write a little script that automatically runs the importer twice. I don't think I will add support for this scenario in the importer. Sorry :)

**Comment by Timoses** [comment]
This would be quite useful, IMO. I'm not willing to enter token/password details into a configuration file. 

So with the current setup, one config file per account containing basically the same information (multiple accounts at the same bank) is needed.
This also means typing in any passwords or tokens as many times as config files (i.e. accounts) exist. This seems unnecessary.

@bnw If you'd think this to be useful, I could take a look at it.
