### ISSUE TITLE
FinTs Import not working with SecureGo and Rheingauer Volksbank (Fiducia)

### ISSUE THREAD

**Issue by joBr99** [bnw/firefly-iii-fints-importer#18]
First of all thanks to @5aint2ero for implementing SecureGo.

I tried to use it and got until "The connection to both your bank and your Firefly III instance could be established."

In the next step i've got the following error message after few seconds:

`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. 9010 (wrt seg 3): Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. Request segments: HKSPA:3:1' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(353): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(312): Fhp\FinTs->sendRequestForAction(Object(Fhp\Action\GetSEPAAccounts), Object(Fhp\Protocol\Message)) #3 /app/index.php(103): Fhp\FinTs->execute(Object(Fhp\Action\GetSEPAAccounts)) #4 /app/TanHandler.php(41): {closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/i in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196`

**Comment by bnw** [comment]
Hm, some ideas:
* Did you use the "go back" or "refresh" buttons of your browser? This might lead to errors.
* Did you use the tool simultaneously in multiple tabs? This may also cause issues.
* Is the error reproducible? Try to start from an empty session. The easiest way to do this is to open the tool in a "private browsing" window in your browser

**Comment by joBr99** [comment]
I've just deleted the docker container and the images and rebuilded it and it is now working, so it seems like this was some sort of caching issue.
