### ISSUE TITLE
Create Docker Image on DockerHub (or another registry)

### ISSUE THREAD

**Issue by cdrfun** [bnw/firefly-iii-fints-importer#19]
Awesome work! I really like your container. One thing though: please create a Docker Image on Dockerhub so anyone can directly get your Docker Container.

There already is an Image from somebody (https://hub.docker.com/r/totti4ever/firefly-iii-fints-importer), but the git repo is several commits behind.
So, for now I've created my own Image on Dockerhub (https://hub.docker.com/r/cdrfun/firefly-iii-fints-importer) which should sync changes between your and my repository.

But I think it's better to create the Image directly from your repo. If you have any questions, feel free to ask.

**Comment by totti4ever** [comment]
Oh, that's mine! Thought I had set it up to also synchronize automatically.
I had manually synchronized it the other day. Thanks for pointing it out and providing an own!

I think it'd be really helpful to set it up on this original repo, indeed!
@bnw, any chance?

**Comment by bnw** [comment]
https://hub.docker.com/r/benkl/firefly-iii-fints-importer :)

**Comment by cdrfun** [comment]
I've deleted my repository.
