### ISSUE TITLE
PushTan error

### ISSUE THREAD

**Issue by kevinkk525** [bnw/firefly-iii-fints-importer#21]
I just tried the importer and got this error after submitting all my data:

```
Notice: Undefined offset: 921 in /app/FinTsFactory.php on line 55

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:56 Stack trace: #0 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(46): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 56
```

Bank is DKB and I used pushTAN

**Comment by bnw** [comment]
Hey,
are you sure that DKB supports pushTAN? Could you try some of the others that sound like they might fit? Like mobileTAN or SecureGoTAN?

**Comment by kevinkk525** [comment]
Same problem with mobileTan and secureGoTan:
```
Notice: Undefined offset: 901 in /app/FinTsFactory.php on line 55

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:56 Stack trace: #0 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(46): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 56
```

I assumed the notification on the android app is pushTAN? Using chipTan works though..

**Comment by bnw** [comment]
I improved the error message in bdc6b386694221972a39270e0a3e096059b5454c. It now shows you which tan modes your bank accepts for the provided credentials.   
I know that for DKB you need to use different credentials depending on the tan mode you want to use. Could this be the issue here?

**Comment by kevinkk525** [comment]
Interesting:
```
Warning: assert(): Your bank did not accept your tan mode 921. Accepted modes are: 910, 911, 912, 913 failed in /app/FinTsFactory.php on line 58

Notice: Undefined offset: 921 in /app/FinTsFactory.php on line 60

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:61 Stack trace: #0 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(101): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 61
```

It seems like DKB does not support pushTan over FinTS anymore? I can use my normal login or the "Legitimations-ID" but it doesn't matter. Same error message.

**Comment by bnw** [comment]
[Here](https://homebanking-hilfe.de/forum/topic.php?t=18555) somebody suggested using the *_p username. Is that what you tried?

I have had good experiences with the dkb technical support. It takes a few days but they were really able to answer in depth technical questions to their api.

**Comment by kevinkk525** [comment]
I get an error with _p username. My login doesn't have _p or _c and that thread is 5 years old.

**Comment by bnw** [comment]
Closed because old. Please reopen, if you have any new ideas.
