### ISSUE TITLE
Allow leaving some fields empty in config.json

### ISSUE THREAD

**Issue by bnw** [bnw/firefly-iii-fints-importer#23]
> If I leave the user id and pin empty it fails with an Exception:
> Fatal error: Uncaught InvalidArgumentException: pin cannot be empty in /vendor/nemiah/php-fints/lib/Fhp/Options/Credentials.php:35 Stack trace: #0 /app/FinTsFactory.php(26): Fhp\Options\Credentials::create('bohmer.push', '') #1 /app/index.php(67): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Options/Credentials.php on line 35
> 
> But saving these two could be a security issue in my opinion. It would be good if one can create general bank settings but still allowing to enter user id and pin afterwards. Actually the CSV importer handles it the same. It uses the same form for entering all data like if no preset is created, just already filling out known fields but leaving unknown fields empty.

https://github.com/bnw/firefly-iii-fints-importer/pull/22#issuecomment-706087736

**Comment by lenucksi** [comment]
This way you could even have a static database with common FinTS connections and base data. Such a source should might be available online.

**Comment by BWohlbrecht** [comment]
I'd love this feature. Any plans on adding it?

**Comment by cmantsch** [comment]
I'd also appreciate such a feature. I'm really uncomfortable storing my bank's credentials in plain text in my computer, so at least user/password should be optional imo.

**Comment by xhess** [comment]
I am also very uncomfortable storing these in clear. I did throw in a little bit of code to check if the password and/or username is missing in the config file and show the config page with only the needed fields showing up.
see #39

**Comment by bnw** [comment]
Thanks to @xhess for implementing this :)
