### ISSUE TITLE
Further improve automatic data fetching 

### ISSUE THREAD

**Issue by totti4ever** [bnw/firefly-iii-fints-importer#25]
With having the chance to save the basic information of connections in a JSON file, this importer made a HUGE step forward!

But I think this could be pushed more forward as I still have to select
* a source account (at least if there are several accounts, like credit cards)
* a target account
* a time period (could be given as xx days back)

I suggest that all of those should be part of a JSON. I know that this would mean that I had to have several information duplicated in the JSONs (same password for credit card and normal account).

If all this is set, update would again be faster, especially in cases where one doesn't have to provide 2nd factor in the 90 days period

**Comment by joBr99** [comment]
I was also thinking about further automation.
- Mapping of source account's to firefly accounts (via JSON file or via automatic mapping based on the IBAN/Name)
- Automatic time period (Last Transaction in Firefly until today)
- If there is a 2nd factor required send a link (via push, email, whatever) to my mobile phone to complete the factor.


The third point would require some sort of enhanced session management, I dont know if this is possible with symfony or if we need to a database to store the ongoing import's. 

@bnw What are your thoughts about that?

**Comment by langfingaz** [comment]
> If there is a 2nd factor required send a link (via push, email, whatever) to my mobile phone to complete the factor.

There is a separate issue about notifications if a 2nd factor is necessary: https://github.com/bnw/firefly-iii-fints-importer/issues/75. I suggest that we continue discussing about 2nd factor notifications there.
