### ISSUE TITLE
Any idea on how to clean description?

### ISSUE THREAD

**Issue by totti4ever** [bnw/firefly-iii-fints-importer#29]
It is delivered like this
`    string(120) "ÜBERTRAG / ÜBERWEISUNGFIXKOSTEN JAEHRLICH (NOVEMBER): KFZ-STEUEREND-TO-END-REF.:NICHT ANGEGEBENRef. WJ222190302739265/3"`

This leads to quite ugly and not easy to read statements in firefly. What I actually need is obviously _FIXKOSTEN JAEHRLICH (NOVEMBER): KFZ-STEUER_ while having _ÜBERTRAG / ÜBERWEISUNG_ and _END-TO-END-REF.:NICHT ANGEGEBENRef. WJ222190302739265/3_ at the end in new lines might be helpful, but is not necessary at all

**Comment by bnw** [comment]
I think finding a single solution that works for everybody is near impossible. Do you think it would suffice for you to be able to configure a regex match & replace that would be applied to all descriptions? That would be relatively easy to implement.

**Comment by totti4ever** [comment]
Do you mean, I could provide a regex like
```
/^(Übertrag \/ Überweisung)(.*)(END-TO-END-REF.*)(Ref\..*)$/gmi
```
and define a replacement like
```
$2 \n[$1 | $3 | $4]
```

and the result would be
```
FIXKOSTEN JAEHRLICH (NOVEMBER): KFZ-STEUER 
[ÜBERTRAG / ÜBERWEISUNG | END-TO-END-REF.:NICHT ANGEGEBEN | Ref. WJ222190302739265/3]
```

That would be more than enough and would absolutely help!

**Comment by dfunke** [comment]
I added some initial support for this, see PR #88
