### ISSUE TITLE
required_session_value failed in /app/FinTsFactory.php

### ISSUE THREAD

**Issue by fenpaws** [bnw/firefly-iii-fints-importer#3]
First of all awesome tool, i hope that you maintain it for a while. I don't like the old fashion import CSV way. Anyway, i tried it out and something wired is happening.

When i launch the tool everything is fine. after i entered my bank data (DKB) and selected "chipTAN optisch" i get the following error messages on screen.

```
Warning: assert(): assert($session->has($required_session_value)) failed in /app/FinTsFactory.php on line 14
Warning: assert(): assert($session->has($required_session_value)) failed in /app/FinTsFactory.php on line 14
Warning: assert(): assert($session->has($required_session_value)) failed in /app/FinTsFactory.php on line 14
Warning: assert(): assert($session->has($required_session_value)) failed in /app/FinTsFactory.php on line 14
```

weirdly enough i can proceed, it find my bank account and my firefly account. It also find the transactions. 
After that, I try to import but i get another error.
```
For 1 transactions, Firefly III reported some problems which are listed below.
These transactions were most likely not imported. 
```
```
    200€ from [REDECTED]
        Sparen
        Sie brauchen mindestens eine Transaktion.
        Beschreibung Feld muss ausgefüllt sein.
        Ungültige Transaktionstyp
```
 I don't know if these to relate or not.

I hope you can help me there.

**Comment by bnw** [comment]
Hi,
thanks for the feedback.
I think the two issues are unrelated. I'll open another issue for the second part.
As to the first part: Unfortunately I cannot reproduce it. Did you, by any chance, use the back & forth buttons of your browser? This could mess things up.

If the problem persist, you could help me debug it by the following: 
Add the line `var_dump($session->all());` at to the beginning of `create_from_session` in app/FinTsFactory.php (e.g. between line 12 & 13). This will dump your session. Post what it says (anonymized) at the step where you get the error.

**Comment by fenpaws** [comment]
So I tested it again, still the same errors. But I added the lines yo said and here is the output. (All anonymized)

I used a different browser and everything, but the issue still exists

```
array(7) { 
    ["bank_username"]=> string(12) "10550XXXXX_c" 
    ["bank_password"]=> string(8) "Lz9GX" 
    ["bank_url"]=> string(45) "https://banking-dkb.s-fints-pt-dkb.de/fints30" 
    ["bank_code"]=> string(8) "12030000" 
    ["bank_2fa"]=> string(3) "911" 
    ["firefly_url"]=> string(23) "https://money.domain.com/" 
    ["firefly_access_token"]=> string(952) "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9..ELwAG43l0xaoU6MNj7afaOCswd5oVcTfbnNOefQ_2NSFLrbgtusFgBxwH04UQuxY4coGL6TKwDqEaw" } 
```

**Comment by rytilahti** [comment]
For the assertion failure, the data is stored in `bank_`-prefixed session variables while foreach asserts for variable names without those.

**Comment by bnw** [comment]
Yes, your right. Thanks to both of you!
