### ISSUE TITLE
FinTS Import Error

### ISSUE THREAD

**Issue by inetplus** [bnw/firefly-iii-fints-importer#32]
Hi,

first of all i am new in using of firefly and want to import account statements from bank "DKB".

i am getting the following error message when i try to import account statements.
could you support me how to solve this issue?

thanks

Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: GuzzleException: cURL error 28: Connection timed out after 150000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php:83 Stack trace: #0 /app/index.php(174): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #1 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php on line 83

**Comment by bnw** [comment]
Hi,
there seems to be a problem reaching your firefly III instance. Double-check the URL you put in and make sure that the firefly III URL is actually reachable from where you are running the importer from. E.g. if you run the importer in a docker container, URLs like 'localhost' might not be correct.

**Comment by inetplus** [comment]
Hi Bnw,

ok. i am double checking it now. coming back with feedack

**Comment by inetplus** [comment]
thanks for your support.
i was able to manage it now.
