### ISSUE TITLE
Bug?/Feature: Transfers between 2 Asset accounts are not handled properly

### ISSUE THREAD

**Issue by 749** [bnw/firefly-iii-fints-importer#33]
Hey There!

great work with the importer so far, keep at it ;-)

I have found that if I import transfer transactions from my giro to my savings account (I have them both as Asset Accounts in FireflyIII), The Importer instead creates a Transaction from my Giro to a new Expense Account (with the my name and the IBAN of the savings account).
Inversely the savings account gets the money from a new revenue Account with the IBAN of the giro and my name.

I would have expected it to create a transfer transaction instead of this convoluted revenue and expense Account setup.

Hope you can help with this!

**Comment by Genygo** [comment]
Hey,
you could create a rule in FireflyIII that change the transaction to a transfer.
That's how i handle this type of transactions
