### ISSUE TITLE
Support Tan 962, 972, 982

### ISSUE THREAD

**Issue by MeikelLP** [bnw/firefly-iii-fints-importer#34]
Hey I don't FinTS but my bank only supports 962, 972, 982

I don't know how much there is to implement but I'm ready to help.

Respectively:
* SMS-TAN 
* Chip-TAN 
* Push-TAN
* Photo-TAN

but maybe the IDs differ

**Comment by MeikelLP** [comment]
Ok I was able to do it via the config file. Maybe the UI should be updated to allow custom IDs

**Comment by bnw** [comment]
Done.
