### ISSUE TITLE
Sparda-BW support

### ISSUE THREAD

**Issue by Pfuenzle** [bnw/firefly-iii-fints-importer#35]
Hi, I tried to use my Bank (Sparda-Bank Baden-Wuerttemberg), but from what I have seen, it only supports mode 997, which is not supported here?

```
Warning: assert(): Your bank did not accept your tan mode 910. Accepted modes are: 997 failed in /app/FinTsFactory.php on line 58

Notice: Undefined offset: 910 in /app/FinTsFactory.php on line 60

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:61 Stack trace: #0 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(101): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 61
```

The Method used for authentication there is called "Sparda Secure App". It does not generate a TAN, but shows info about the process and lets the user either accept or reject the access. I also tried to select other methods by manually changing their ID, but I obviously always get an error

```Fatal error: Uncaught RuntimeException: Need to login (DialogInitialization) before executing other actions in /vendor/nemiah/php-fints/lib/Fhp/FinTs.php:280 Stack trace: #0 /app/index.php(158): Fhp\FinTs->execute(Object(Fhp\Action\GetSEPAAccounts)) #1 /app/TanHandler.php(41): {closure}() #2 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #3 /app/index.php(155): App\TanHandler->__construct(Object(Closure), 'list-accounts', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/FinTs.php on line 280```

Would it be possible to support this method/bank?

Thanks a lot

**Comment by bnw** [comment]
Hi,
I added tan option 997 to the list. Unfortunately, I am unable to test it.
If it does not work for you, feel free to reopen the issue.
