### ISSUE TITLE
Feature Request: Search for Bank in form

### ISSUE THREAD

**Issue by BWohlbrecht** [bnw/firefly-iii-fints-importer#37]
Hello,

I noticed hbci4java is used in the backend. Hbci4java contains a more or less up to date list of FinTS endpoint-URLs for many banks.
This could be used for a search option in the config form to find banks and automatically set the FinTS-URL.

Opinions?

**Comment by bnw** [comment]
Hi,
hbci4java is not used in the backend. This is a php based app using https://github.com/nemiah/phpFinTS
I had a quick look at https://github.com/hbci4j/hbci4java but could not find any such list.
If you can point me to any list with enpoint URLs, I'll happily add them as a link. Should save most users a few minutes of research :)

**Comment by kompetenzbolzen** [comment]
https://github.com/hbci4j/hbci4java/blob/master/src/main/resources/blz.properties seems promising

**Comment by BWohlbrecht** [comment]
> 
> 
> https://github.com/hbci4j/hbci4java/blob/master/src/main/resources/blz.properties seems promising

That's the one. Sorry, I must have seen a ghost then. :D
