### ISSUE TITLE
Fatal error without further notice

### ISSUE THREAD

**Issue by Charliopoulos** [bnw/firefly-iii-fints-importer#45]
For the comdirect bank (https://fints.comdirect.de/fints) it just throws this error:

Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthaelt Fehler. 9800 (global): Dialog abgebrochen 9010 (global): Zugriff auf BPD nicht moeglich. in /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors() #1 /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(576): Fhp\FinTs->sendMessage() #2 /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(602): Fhp\FinTs->ensureBpdAvailable() #3 /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(464): Fhp\FinTs->ensureTanModesAvailable() #4 /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php(55): Fhp\FinTs->getTanModes() #5 /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode() #6 /var/w in /var/www/html/firefly-iii-fints-importer/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196

**Comment by bnw** [comment]
Hm, in #8 and #9, Comdirect seems to be working. 
Possibly you are using a wrong URL or BLZ?  
Maybe @totti4ever or @maltechx could report if Comdirect is still working for them and what settings to use?

**Comment by Charliopoulos** [comment]
BLZ is correct, though I am not sure about the URL, just found this their webpage (https://www.comdirect.de/cms/sicherheit-software-banking-fints.html):

> Den HBCI-Server der comdirect erreichen Sie auf: https://fints.comdirect.de/fints
In das „Benutzerkennung-Feld“ Ihre Zugangsnummer eingeben, die Sie auch im Online-Banking verwenden. Das Feld „Kunden-ID“ bitte freilassen.

I would appreciate any hints. Also, do I have to activate the API access? (for every account? (I have 3 accounts in comdirect))

**Comment by maltechx** [comment]
Yes for me it is working. I'm not regularly using it, but just pulled the current state an tested it.  
My settings:
URL: https://fints.comdirect.de/fints
BLZ: 20041144
Two-Factor Method: mobileTAN (901)

**Comment by Charliopoulos** [comment]
Ok, now it worked. It was indeed the BLZ, I had a typo. 🤦‍♂️
