### ISSUE TITLE
How to find out the FinTS API of my bank? And the answer to the question!

### ISSUE THREAD

**Issue by SoulEater45** [bnw/firefly-iii-fints-importer#46]
I have been struggling to find the FinTS URL of my bank and nearly gave up. There isn't a nice database where everything is listed and some bank do have it on their homepage or in the online banking menu, but some banks are quite mysterious...
Nevertheless, if someone is eager to find the URL, this handy dandy tool can maybe help you: https://github.com/dr-duplo/python-fints-url
I just put in the BLZ and puf, there it is :D

**Hope it helps someone in the search and it would be nice to put it in the Readme :)**

**Comment by bnw** [comment]
I added it to the field in the form. Thanks for the suggestion :)
https://github.com/bnw/firefly-iii-fints-importer/commit/4684feae603b9be71741bc9bf05024abab7fb5e6

**Comment by greenbigfrog** [comment]
The data source fints-url uses appears to have moved or something.
A quick `ctrl + f` in https://raw.githubusercontent.com/jhermsmeier/fints-institute-db/master/fints-institutes.json was a much faster solution anyway :smile:
