### ISSUE TITLE
Add more information to account selection

### ISSUE THREAD

**Issue by SuPuL** [bnw/firefly-iii-fints-importer#49]
Hi, 
Thanks for your project. For me, it isn't easy to distinguish which account to import. So I've added more information on each entry in my local env. Unfortunately, I'm not allowed to create a branch and pull request, so I've attached a [account-patch.txt](https://github.com/bnw/firefly-iii-fints-importer/files/7111337/account-patch.txt). 

It will be awesome if you consider integrating this one. 

Greetings

**Comment by bnw** [comment]
Hi,
thanks! I added your suggestion :)
https://github.com/bnw/firefly-iii-fints-importer/commit/b789f28f5066a3d4b3903a8e0be792a8d842afd6
