### ISSUE TITLE
Misleading Message about Connection to Firefly III

### ISSUE THREAD

**Issue by quittung** [bnw/firefly-iii-fints-importer#52]
After setup this message will be shown:
![grafik](https://user-images.githubusercontent.com/10237613/142341944-17011f08-2e91-4101-aac5-2f6af7cbc79c.png)

But if the Firefly III url or access token is incorrect, an error like this will still be shown on the next page:
![grafik](https://user-images.githubusercontent.com/10237613/142342200-589df056-d282-469c-ad71-cf7082542cfe.png)

This made troubleshooting a wrong access token a bit more confusing than it had to be. Maybe the message could be changed to:
`The connection to your bank was established.`

Other than that it works great, thanks to everyone that worked on this importer!

**Comment by bnw** [comment]
You're right! Thank you :)
Fixed.
