### ISSUE TITLE
Support more 2FA/TAN methods

### ISSUE THREAD

**Issue by davidclemens** [bnw/firefly-iii-fints-importer#53]
Hei there,

Thanks a lot for developing the FinTS importer.
I'm trying to setup the connection to the [`GLS Gemeinschaftsbank`](https://www.gls.de/privatkunden/), but it seems they require a different TAN method than currently implemented [`app/public/html/collecting-data.twig`](https://github.com/bnw/firefly-iii-fints-importer/blob/b789f28f5066a3d4b3903a8e0be792a8d842afd6/app/public/html/collecting-data.twig).

#### What I did:
- [x] checked that `GLS Gemeinschaftsbank` supports FinTS and is listed [here](https://subsembly.com/banken.html)
- [x] found the connection details listed on [their website](https://www.gls.de/unternehmen-institutionen/konto-zahlungsverkehr/sepa-zahlungsverkehr/daten-zum-onlinebanking/)
- [x] setup a configuration `.json` file.
- [ ] tried all TAN methods that are implemented as in [`app/public/html/collecting-data.twig`](https://github.com/bnw/firefly-iii-fints-importer/blob/b789f28f5066a3d4b3903a8e0be792a8d842afd6/app/public/html/collecting-data.twig)

#### The Error I get:
```
Warning: assert(): Your bank did not accept your tan mode 921. Accepted modes are: 942, 962, 972, 982 failed in /app/FinTsFactory.php on line 58

Notice: Undefined offset: 921 in /app/FinTsFactory.php on line 60

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:61 Stack trace: #0 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(82): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 61
```

#### What I think is going on
So it seems that only TAN modes `942`, `962`, `972` or `982` are supported, neither of which is implemented in [`app/public/html/collecting-data.twig`](https://github.com/bnw/firefly-iii-fints-importer/blob/b789f28f5066a3d4b3903a8e0be792a8d842afd6/app/public/html/collecting-data.twig), if i read correctly.

I don't really understand, why smsTAN or mobileTAN don't work, since I have them activated and use them for transactions on a day to day basis.

Also SecureGo TAN is supported by GLS and I'm currently activating it (I need to wait on physical mail). This is great, since SecureGo seems to be implemented as `944`. However `944` is not among the TAN modes listed in the error message above. So I'm again confused.

#### My questions
So could one of these methods mentioned above be implemented?
Or am I totally wrong about this?

#### More info:
Firefly-iii 5.6.4 in a Docker container
FinTS inside a Docker container with the following docker-compose:
```yaml
importer-fints:
  image: benkl/firefly-iii-fints-importer
  restart: unless-stopped
  volumes:
    - <redacted>:/app/configurations
  ports: 
    - <redacted>:8080
```
The FinTS importer configuration `.json`:
```json
{
  "bank_username": "<redacted>",
  "bank_password": "<redacted>",
  "bank_code": "43060967",
  "bank_url": "https://hbci-pintan.gad.de/cgi-bin/hbciservlet",
  "bank_2fa": "920",
  "firefly_url": "<redacted>",
  "firefly_access_token": "<redacted>"
}
```

**Comment by bnw** [comment]
You can try any value in the `bank_2fa`-field. It is not limited to the set listed in `app/public/html/collecting-data.twig`  
Nonetheless, I have added these to the option list :)

If it does not work, please reopen the issue.

**Comment by davidclemens** [comment]
Ahh, that's good to know.

I quickly tried one of the supported methods, which got me further in the dialogues.
However, now I'm stuck with the other problem I have here: #54.

So I can't fully validate if this "new" 2FA method will work in the end.
