### ISSUE TITLE
Error connecting to Firefly during API GET request

### ISSUE THREAD

**Issue by davidclemens** [bnw/firefly-iii-fints-importer#54]
Hei again,

and again thanks a lot for developing the FinTS importer.
I'm trying to setup the connection to the [`ING`](https://www.ing.de) and the connection to ING seems to work, but I get an `403 Forbidden` error when trying to read the Firefly accounts via their API.

#### The Error I get:
```
Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: GuzzleException: Client error: `GET http://firefly.lan/api/v1/accounts?type=asset&page=1` resulted in a `403 Forbidden` response: <html> <head><title>403 Forbidden</title></head> <body> <center><h1>403 Forbidden</h1></center> <hr><center>openrest (truncated...) in /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php:83 Stack trace: #0 /app/index.php(189): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #1 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php on line 83
```

#### What I think is going on
To me it seems like there is a problem with the authentication of the Firefly API.

#### What I tried:
- [x] successfully manually sent a GET request with the bearer token to get a list of the accounts in my Firefly instance. So the Firefly URL and token should be correct.

#### My questions
Are there any insights into this problem? Any idea how to fix it?

#### More info:
Firefly-iii 5.6.4 in a Docker container, accessed locally via http.
FinTS inside a Docker container with the following docker-compose:
```yaml
importer-fints:
  image: benkl/firefly-iii-fints-importer
  restart: unless-stopped
  volumes:
    - <redacted>:/app/configurations
  ports: 
    - <redacted>:8080
```
The FinTS importer configuration `.json`:
```json
{
  "bank_username": "<redacted>",
  "bank_password": "<redacted>",
  "bank_code": "50010517",
  "bank_url": "https://fints.ing.de/fints",
  "bank_2fa": "NoPsd2TanMode",
  "firefly_url": "<redacted>",
  "firefly_access_token": "<redacted>"
}
```

**Comment by Athesis** [comment]
Hey,

I had a similar issue, I solved it by creating a new access token in Firefly III

**Comment by davidclemens** [comment]
Thanks for the suggestion @Athesis. I tried as you suggested, but without any luck.

Just to clarify: With "token" I mean a token generated via the Firefly UI like so:
Sidebar -> Options -> Profile -> OAuth -> Personal Access Tokens

Not like so:
Sidebar -> Options -> Profile -> Command line token

That is the correct way to do it, I assume!?

**Comment by Athesis** [comment]
@davidclemens Yes, it was this token I renewed to solve it.

**Comment by gunrunner20** [comment]
Worked for me as well, thanks a lot!

**Comment by bnw** [comment]
Hey @davidclemens, did you manage to find a solution?

**Comment by davidclemens** [comment]
Thanks for the suggestions and also for following up on this @bnw.

Sadly no.
I tried multiple times to renew the token (and with "renew" I mean creating a new one and deleting the old one in the Firefly III UI), without success.

Do you have any pointers to what else I could try? Any logs that could reveal more details?

**Comment by bnw** [comment]
Here are a couple ideas:  
* Is the importer up to date?
* Try to see if any additional information appears in the Firefly III logs (see ["How do I enable debug mode?"](https://docs.firefly-iii.org/firefly-iii/faq/other/) ).
* If this does not yield any insights, try to capture the exact request that is being sent to Firefly III.  
  Then we examine the request. If its faulty, the importer has a problem. If the request is fine, the problem lies on the Firefly III side.  
  To do this, modify the locally installed `GetAccountsRequest.php` and add the following line to the beginning of the `catch`-block in the `get()` method: `var_dump($e->getRequest());`.
  When the error is triggered now, you should see all the requests data.

**Comment by davidclemens** [comment]
Thanks for all the pointers.

Upon further inspection, it - of course - turns out to be a dumb mistake on my side with my local DNS setup and Docker: 
My local DNS is somehow not honored within the Docker environment and therefore the connection to Firefly could not be established. Using raw IPs solved it for me.

Thanks for your help and sorry for raising the alarm.
