### ISSUE TITLE
[Config]  Firefly III URL

### ISSUE THREAD

**Issue by fockr** [bnw/firefly-iii-fints-importer#64]
Hi there!
I am currently trying to configure the importer with my firefly-iii installation. The bank is recognized flawlessly. Now the step after that fails because apparently the firefly-iii URL is invald.

`
Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: Error accessing "https://localhost/firefly-iii/app/api/v1/accounts?type=asset&page=1&limit=250". Status code is 404. Body is: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found</h1> <p>The requested URL was not found on this server.</p> <hr> <address>Apache/2.4.41 (Ubuntu) Server at localhost Port 443</address> </body></html> in /var/www/html/firefly-iii/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/Request.php:212 Stack trace: #0 /var/www/html/firefly-iii/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(89): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() #1 /var/www/html/firefly-iii/firefly-iii-fints-importer/app/ChooseAccount.php(37): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #2 /var/www/html/firefly-iii/firefly-iii-fints-importer/app/index.php(57): App\StepFunction\ChooseAccount() #3 {main} thrown in /var/www/html/firefly-iii/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 212`

The URL I configured in the settings was https://localhost/firefly-iii/app. I also tried simply https://localhost/firefly-iii but nothing would work. It keeps responding with status code 404.

What am I doing wrong?

Thanks in advance!

**Comment by bnw** [comment]
Hi,
sorry for the late reply. Could you check the following:
* Whats your FireflyIII version?
* Make sure that accessing the API is possible under the URL in the error message. You could e.g. try to reach the `​/api​/v1​/about` endpoint using curl (see https://api-docs.firefly-iii.org). Maybe there are some routing problems arising from the fact, that you have Firefly running in a subfolder, instead of its own host?
