### ISSUE TITLE
DKB not worked for me

### ISSUE THREAD

**Issue by Hapyr** [bnw/firefly-iii-fints-importer#67]
Connection to bank works fine for me. But after TAN entered i got this error:
```
Fatal error: Uncaught Error: Call to undefined function GrumpyDictator\FFIIIApiSupport\Request\str_contains() in /vendor/firefly-iii/api-support-classes/src/Request/Request.php:349 Stack trace: 
    #0 /vendor/firefly-iii/api-support-classes/src/Request/Request.php(200): GrumpyDictator\FFIIIApiSupport\Request\Request->handleException(Object(GuzzleHttp\Exception\ConnectException)) 
    #1 /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(89): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() 
    #2 /app/ChooseAccount.php(37): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() 
    #3 /app/index.php(57): App\StepFunction\ChooseAccount() 
    #4 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 349
```

![image](https://user-images.githubusercontent.com/23398802/163840067-47445468-374b-4d3e-a78e-32cf0d7e611a.png)

**Comment by bnw** [comment]
Good news: I could reproduce and fix you error.  
Bad news: The error occurs during reporting that the connection to your fireflyIII instance was unsucessful. At least, with the fix you will be able to see the actual error message. If this does not guide you to the problem, please reopen :)

**Comment by Hapyr** [comment]
Hi, thanks for the quick fix. That runs for now :)
The real problem now was that my firefly api (firefly complete actually) is not accessible from the FinTS container. I host firefly and the FinTS container locally. But without compose setting "network_mode: host" the 127.0.0.1:8090 (firefly) is not reachable from the FinTs container.
