### ISSUE TITLE
Remove one of the two example.json

### ISSUE THREAD

**Issue by Bur0k** [bnw/firefly-iii-fints-importer#69]
There are currently two `example.json` in the repository.
1. `app/configurations/example.json`
2. `data/configurations/example.json`

This confuses people (and me while developing :) ).

Which one of these two could be removed? Or do we need both?
Personally i would remove the one in the `app` directory, since normal configs are also in `data`

**Comment by bnw** [comment]
Yes, you are right. Thanks :+1:
