### ISSUE TITLE
Descriptions are not always parsed correctly

### ISSUE THREAD

**Issue by rytilahti** [bnw/firefly-iii-fints-importer#7]
I have some cases where the description is not parsed properly even when they exist, one example:
```
[bookingText:protected] => GUTSCHR. UEBERWEISUNG
[description1:protected] => EREF+2018XXXXXXX 
[description2:protected] => [structuredDescription:protected] => Array ( [EREF] => 2018XXXXXXXXX )
```

Import error: `The description field is required.`

**Comment by bnw** [comment]
I fixed a bug in 7782e096. In the above case, the description sent to firefly should now be "GUTSCHR. UEBERWEISUNG".
