### ISSUE TITLE
Problems with Sparkasse after forced change from tanJack to S-pushTAN

### ISSUE THREAD

**Issue by Athesis** [bnw/firefly-iii-fints-importer#73]
Poorly, Sparkasse forcing their customers away from "tanJack" systems to the S-pushTAN App. With this change, the import of data from Sparkasse with fints-importer also stopped working with the following error:
`Warning: Undefined array key "skip_transaction_review" in /var/www/html/firefly-iii-fints-importer/app/ConfigurationFactory.php on line 34

Warning: Undefined array key 910 in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php on line 60

Fatal error: Uncaught Error: Call to a member function needsTanMedium() on null in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php:32 Stack trace: #0 /var/www/html/firefly-iii-fints-importer/app/CollectData.php(50): App\FinTsFactory::create_from_session() #1 /var/www/html/firefly-iii-fints-importer/app/index.php(45): App\StepFunction\CollectData() #2 {main} thrown in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php on line 32`

Is there a chance to get fints-importer back running?

**Comment by JuliusFreudenberger** [comment]
I do not have a tanJack device and only use the S-pushTAN App.
In the importer I specified the TAN method 921. I get to select the TAN device - which in my case is only one. However I did never have to enter a TAN.
Does this information help you?

**Comment by Athesis** [comment]
Hello Julius,

Thanks for your answer. I now spoke as well to the IT Department of my Sparkasse, the problem was, they do not change fints configurations on this “Forced change”-Assistant and basically left it on a broken tanJack (2fa 910). It works now! Thank you!
