### ISSUE TITLE
Config Problem Template json

### ISSUE THREAD

**Issue by Becksta0815** [bnw/firefly-iii-fints-importer#80]
Hi,

im trying out to configure an account template, but it goes wrong with:
`
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 29
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 30
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 31
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 32
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 33
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 34
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 35
Warning: Trying to access array offset on value of type null in /app/ConfigurationFactory.php on line 36`

My template looks like this:
`{
  "bank_username": "XXXXXX",
  "bank_password": "XXXXX",
  "bank_code": "50010517",
  "bank_url": "https://fints.ing.de/fints",
  "bank_2fa": "NoPsd2TanMode",
  "firefly_url": "172.21.0.5:8080",
  "firefly_access_token": "XXXX",
  "skip_transaction_review": "false",
  "choose_account_automation":
  {
    "bank_account_iban": "",
    "firefly_account_id": "",
    "from_to_comment": "The following values will be passed directly into DateTime",
    "from": "now - 7 days",
    "to": "now"
  }
}`

i dont get, whats wrong. Maybe someone can help me with this? 

regards
Daniel

**Comment by bnw** [comment]
Hi,
it looks like either the wrong file was read in, or the parsing of the file went very wrong.
* To rule out the first case, please double check that the file can be accessed from the importer. If you use docker, maybe something went wrong when copying / mounting the file into the container? Try to open an shell in the running container and verify that the file is there and contains what you think it does.
* To debug the second possibility: Add the following to `app/ConfigurationFactory.php` line 27: `var_dump($contentArray);`. Then, in addition to the above error message you posted you will see what php parsed from your json file. Maybe it's not correctly formatted or something silly happend with the character encoding?

**Comment by bnw** [comment]
I'll close the issue for now. Feel free to reopen if the problem persists.
