### ISSUE TITLE
Wrong balance of account after initial import

### ISSUE THREAD

**Issue by marlemion** [bnw/firefly-iii-fints-importer#81]
Hi, I have successfully implemented firefly and firefly fints importer. Thanks a lot for this excellent work! I also managed to import data from two bank accounts (DKB and Deutsche Bank). However, the balances shown in firefly do not match the balance shown on my bank account apps.

I am fairly new to firefly. After reading some documentation, I have tried the reconcilation function, but that apparently did not work. What is the correct way to initially import by fints? Reason for the wrong balance might be that I cannot import all of the transactions starting from the first day of the account. Hence, there is a cut off, which might not be taken into account.

Nevertheless, in hibiscus, the amounts are correctly imported.

Any hint? Thanks!

**Comment by JuliusFreudenberger** [comment]
What I did, when I started using this combination (and which could lead to the problem you're describing) is the following:
Select a starting date from which to import. When you add the bank account in firefly you can select a starting balance and a date for it. Enter the balance your bank account has at this specific date and continue importing from this date onward. This works for me for more than a year now.

**Comment by marlemion** [comment]
Thanks for the hint. Nevertheless I was wondering why hibiscus can handle the same situation very well, and the PHP FinTS implementation apparently not (hibiscus uses JAVA). Maybe a certain field is not read? Do the transaction objects provide the absolute account sum?
