### ISSUE TITLE
FinTS Importer doess not recognize asset accounts

### ISSUE THREAD

**Issue by marlemion** [bnw/firefly-iii-fints-importer#82]
I have set up several accounts as asset accounts. Lets say I have set up a DKB, DB24, and DIBA. All have a respective IBAN placed in the account information.

I have also added respective json files to gather the data from the bank. Some of the transactions received e.g. from DKB will transfer money to DB24. As DB24 is set up as an asset account and the respective IBAN number is to be found in the data from the bank, at least according to the documentation of the CSV importer, a transfer should be created instead of a transaction. Furthermore, in this case no revenue account 'DKB' should be created.

However, unfortunately, the FinTS importer does not seem to do so. I have also tried to match the correct name of the account according to the information found in data from the bank, but that does not change the behaviour.

Has this not been implemented? If not, how could this be done? Does FinTS use the general CSV importer or does it have its own code base?

Thanks for any help!

**Comment by JuliusFreudenberger** [comment]
I use this possibility, too.
The CSV importer is a completely different project with different codebase and their documentation does not necessarily apply for the fints-importer.

**Comment by marlemion** [comment]
Yes, thanks. Nevertheless, I have a rather complicated setup with 5 different accounts. So I have to setup two rules for each combination (Withdrawal and Deposit) and mark one to be deleted (category). The last step of deletion of the double entry does unfortunately not work, as the fints importer crashed in case the transaction (or then transfer) is deleted shortly after import. So I have to run one rule by hand.

**Comment by bnw** [comment]
Hi,
this is a feature that is not implemented yet. 
I think it would require only small changes. Unfortunately, I'm not sure when I'll have time to work on this. If you want to contribute, I'm happy to merge your changes :)
Some pointers: 
* I believe API wise, there is no difference between a transaction and a transfer. Both are added with the same [endpoint](https://api-docs.firefly-iii.org/#/transactions/storeTransaction).
* I think one needs to supply both the `source_id` and `destination_id` for a transaction to become a transfer.
* To find out the other accounts id, one would have to query the Firefly's API.
* The API request for adding transactions is assembled in: https://github.com/bnw/firefly-iii-fints-importer/blob/master/app/TransactionsToFireflySender.php
