### ISSUE TITLE
1822-direkt 

### ISSUE THREAD

**Issue by JokerGermany** [bnw/firefly-iii-fints-importer#85]
At the moment i test if firefly could be a replacement for gnucash:

It looks like i need other tan methods for the 1822-direkt.
I need the Method 903

Attached are the available Tan methods from aqbanking
![1822](https://user-images.githubusercontent.com/30293477/214288682-8f69939c-0e01-4a12-a7e8-7a11f05ebe1f.png)

**Comment by JokerGermany** [comment]
Looks like you just have to edit https://github.com/bnw/firefly-iii-fints-importer/blob/master/app/public/html/collecting-data.twig
Will test it and then make a pr.

**Comment by wedganw** [comment]
Would love to see 1822-direkt to work with FireFly.

I've just tested it out but got the following error:

`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9120 (global): Nachricht nicht erwartet. 9800 (global): Dialoginitialisierung abgebrochen. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(263): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /app/Login.php(23): Fhp\FinTs->login() #4 /app/TanHandler.php(41): App\StepFunction\{closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/Login.php(21): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #7 /app/index.php(53): App\StepFunction\Login() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`

**Comment by bnw** [comment]
@wedganw Could you describe during which step of the import this occurred?  
Also, please make sure not to use the browsers "back" and "forth" buttons during the entire importing process.

**Comment by wedganw** [comment]
@bnw  Nevermind. Seems like the issue was my browser.

I've tested it again from another machine and it worked flawlessly.

So it seems that you really just have to change the value like mentioned above.

Thanks for the fast reply on this ;)

**Comment by bnw** [comment]
Nice :D
Maybe the same as in your original screenshot?

**Comment by JokerGermany** [comment]
okay will do it, but perhaps it needs to replaced if other banks use the same method
