### ISSUE TITLE
DKB - Die Nachricht hat nicht die erwartete Nachrichtennummer. 9010

### ISSUE THREAD

**Issue by blue-kaleidoscope** [bnw/firefly-iii-fints-importer#87]
Hi,

I just tried to access my statements on DKB with the following settings:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/56046815/223688636-d4b88c11-86a6-4626-86c6-61736161d664.png">

After clicking "Submit" I could choose my smartphone from the dropdown to create a TAN. After that I was shown the following information:
```

Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. 9010 (wrt seg 3): Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. Request segments: HKSPA:3:2' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /app/ChooseAccount.php(22): Fhp\FinTs->execute(Object(Fhp\Action\GetSEPAAccounts)) #3 /app/TanHandler.php(41): App\StepFunction\{closure}() #4 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #5 /app/ChooseAccount.php(19): App\TanHandler->__construct(Object(Closure), 'list-accounts', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #6 /app/index.php(57): App\StepFunction\ChooseAccount() #7 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170
```

**Comment by KidA90** [comment]
I got a similar error message fetching my bank statements from DKB as well as comdirect. It happened with dockerized Firefly III versions 5.7.18, 5.8-alpha and 6.0.
I don't know what went wrong, but the solution for me was to generate a new access token for the FinTS importer in Firefly III.

**Comment by bnw** [comment]
Hm,
the error looks like there was a communication error between the importer and the bank.
@blue-kaleidoscope, could it be a network problem at your end? If in the communication between the bank and the importer messages got lost, this might cause such an error message.

If this seems unlikely, we have to debug further.
In what step did the error message occur?

**Comment by blue-kaleidoscope** [comment]
I tried it this morning again and *magic* it worked. Same setup, same server, same network... don't ask me why.
