### ISSUE TITLE
Importer broken since Regex introduction

### ISSUE THREAD

**Issue by KidA90** [bnw/firefly-iii-fints-importer#90]
Since the introduction of Regular Expression for Description Manipulation, the importer is broken.
Regardless of filling in a Regex expression or not, the importer throws the following error after collecting the transactions from the bank and importing them into Firefly III:

Fatal error: Uncaught TypeError: App\TransactionsToFireflySender::__construct(): Argument #5 ($regex_match) must be of type string, null given, called in /app/RunImport.php on line 38 and defined in /app/TransactionsToFireflySender.php:22 Stack trace: #0 /app/RunImport.php(38): App\TransactionsToFireflySender->__construct(Array, '192.168.130.71:...', 'eyJ0eXAiOiJKV1Q...', 178, NULL, NULL) #1 /app/index.php(65): App\StepFunction\RunImport() #2 {main} thrown in /app/TransactionsToFireflySender.php on line 22

**Comment by bnw** [comment]
Hi,
I could not reproduce your crash. Based on the stack trace I tried to create a fix. Please reopen the issue, if the problem persists for you :)

**Comment by KidA90** [comment]
Thank you for your fast reply! I found the issue: I use JSON templates to store the connection data to my bank accounts. I haven't updated the JSONs in while so they didn't contain the parameter for the Regex matching. After adding the (empty) parameter  "description_regex_match" and "description_regex_replace" to the JSON files, the import did work again.

**Comment by greenbigfrog** [comment]
I can confirm adding the empty strings works. Perhaps it should assume them being empty instead of hard crashing if missing?
