### ISSUE TITLE
Unauthorized since this month

### ISSUE THREAD

**Issue by MeikelLP** [bnw/firefly-iii-fints-importer#91]
I recently moved states in Germany and paused my monthly Firefly import.

Sadly my bank is now returning: 
```
Status code is 401. Body is: {"message":"Unauthenticated","exception":"AuthenticationException"}
```

I didn't change anything in my setup. I even updated to the latest master branch & recreated the docker image. I talked to my bank today. They said they didn't change anything (default support answer). I doubt the issue comes from this code but I don't know where to ask for help elsewhere.

It's about the `Volksbank Rhein-Ruhr` ([772](https://subsembly.com/banken.html))

**Comment by bnw** [comment]
Hm, are you using the config-yaml file? If yes, could you try to run the import without that file, entering all data as you go?
During which step of the import, did this error occur?

**Comment by MeikelLP** [comment]
After the "succesfully tested connection to the bank" step.

I promise you I did not touch the file.
I assume my bank did upgrade to some newer FinTS protocol (and dropped support for the old)? But I don't know anything about FinTS so this is just a general assumption.

**Comment by MeikelLP** [comment]
I tried to do it with the manual configuration (via UI) with the exact same values as the json file. Same error

**Comment by MeikelLP** [comment]
Well I just noticed this error does not come from my bank. The error comes from Firefly.

Maybe my access token expired?

**Comment by MeikelLP** [comment]
Well it was just my access token which expired I assume. I just created a new one and it worked. Sadly Firefly shows no expiration of the token
